### PR TITLE
support and test the cortex-m7f-sp

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3943a79 with merge 2425616...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 43f91fa with merge 43f91fa...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135354494)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 951ba2b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 951ba2b with merge 951ba2b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135472852)

**Pull request merged**
