### PR TITLE
ci: run x86_64 target on containers

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b24ba56 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b24ba56 with merge b24ba56...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/126806592)

**Pull request merged**
