### PR TITLE
travis: add more test targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 58f427f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 58f427f with merge 58f427f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135341580)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e784d75 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e784d75 with merge e784d75...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135345908)

**Pull request merged**
