### PR TITLE
assert that AR and CC are set by the user

### PR DESCRIPTION
**Pull request by japaric**
if you forget them you'll likely get a compiler or linker error anyway.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c046db7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c046db7 with merge c046db7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/127318708)

**Pull request merged**
