### PR TITLE
support the cortex-m7f

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b0d634c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b0d634c with merge b0d634c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135473795)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bb31d8b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bb31d8b with merge bb31d8b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135476958)

**Pull request merged**
