### PR TITLE
travis: nm - print only defined global symbols

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3083a92 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3083a92 with merge 3083a92...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135348235)

**Pull request merged**
