### PR TITLE
compile intrinsics that rely on a SP FPU

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cd369e0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cd369e0 with merge 9d01405...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135351394)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit be7e8c8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit be7e8c8 with merge 3f61425...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135353578)

**Pull request merged**
