### PR TITLE
better summary of symbols

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5c3b694 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5c3b694 with merge 5c3b694...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/143481880)

**Pull request merged**
