### PR TITLE
travis: show summary of symbols using nm

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a4b7f53 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a4b7f53 with merge a4b7f53...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135346348)

**Pull request merged**
