### PR TITLE
optimize for CPU

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit f8239e0 with merge 5f68c48...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135329094)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 9fbff28 with merge de64c11...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135329706)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3b0ce7e with merge 5075f0e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135331448)

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit f094a11 with merge f094a11...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135340366)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 02131cd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 02131cd with merge 02131cd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/compiler-rt.rs/builds/135340688)

**Pull request merged**
